WebApplicationASP/Models/ErrorViewModel.cs
namespace WebApplicationASP.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

WebApplicationASP/Models/TruckData.cs
namespace WebApplicationASP.Models;

public class TruckData
{
    public string NO_JOB { get; set; }
    public string PLAT_NO { get; set; }
    public string NO_SPMK { get; set; }
    public DateTime GET_IN_DATE { get; set; }
    public DateTime GET_OUT_DATE { get; set; }
    public DateTime TIME { get; set; }
}

WebApplicationASP/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using WebApplicationASP.Models;

namespace WebApplicationASP.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

WebApplicationASP/Controllers/TruckDataController.cs
using System.Text.Json.Serialization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using WebApplicationASP.Models;

namespace WebApplicationASP.Controllers;

public class TruckDataController: Controller
{
    private static readonly HttpClient client = new HttpClient();
    private const string apiUrl = "https://ptosm.pelindo.co.id/api/monitoring/TruckMonitoring/getListDTPub";

    public async Task<IActionResult> GetTruckData()
    {
        string offset = "0";
        string limit = "10";
        string cari = "";
        string token = "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI1Mjk0OSIsInVzZXJuYW1lIjoiMzkyMTExOTgyIiwiaGFrX2Frc2VzX2lkIjozMTQzLCJrZF9yZWdpb25hbCI6MTMzMCwia2RfY2FiYW5nIjo2MSwia2RfdGVybWluYWwiOjYsIm5tX3JlZ2lvbmFsIjoiUFQgUEVMSU5ETyBNVUxUSSBURVJNSU5BTCIsIm5tX2NhYmFuZyI6IlBUIFBFTElORE8gTVVMVEkgVEVSTUlOQUwiLCJubV90ZXJtaW5hbCI6IlRFUk1JTkFMIEpBTVJVRCIsInBlcnNvbl9hcmVhIjoiMTMzMCIsInBlcnNvbl9zdWJfYXJlYSI6IjA1MDIiLCJpYXQiOjE2ODQ4MTcyNDAsImV4cCI6MTY4NDkwMzY0MH0.6MJF2UpLWcBwZDac98ghvWAdOyVyrZU1LLzDKpPK6aDqajxliiXu-IeWQ6uzAsgGeCsVh_tCUA0mn7WO7pDYIA";

        string requestUrl = $"{apiUrl}?offset={offset}&limit={limit}&cari={cari}&token={token}";

        HttpResponseMessage httpResponseMessage = await client.GetAsync(requestUrl);
        if (httpResponseMessage.IsSuccessStatusCode)
        {
            var responseData = await httpResponseMessage.Content.ReadAsStringAsync();
            var jsonResponse = JObject.Parse(responseData);
            var dataArray = jsonResponse["result"]["data"];
            var truckDataList = dataArray.ToObject<List<TruckData>>();
            return View("GetTruckData", truckDataList);
        }
        else
        {
            return StatusCode((int)httpResponseMessage.StatusCode);
        }
    }
}

WebApplicationASP/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    Home
</div>

WebApplicationASP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - WebApplicationASP</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/WebApplicationASP.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplicationASP</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="TruckData" asp-action="GetTruckData">Data Truck</a>
                        </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2023 - WebApplicationASP - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebApplicationASP/Views/TruckData/GetTruckData.cshtml
@model System.Collections.Generic.List<WebApplicationASP.Models.TruckData>?

<!DOCTYPE html>
<html>
<head>
    <title>Truck Data</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
</head>
<body>
    <div class="container">
        <h1>Truck Data</h1>
        <table class="table">
            <thead>
                <tr>
                    <th>KODE TRUK</th>
                    <th>NOPOL</th>
                    <th>NO SPMK</th>
                    <th>TGL GET IN</th>
                    <th>TGL GET OUT</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var truck in Model)
                {
                    <tr>
                        <td>@truck.NO_JOB</td>
                        <td>@truck.PLAT_NO</td>
                        <td>@truck.NO_SPMK</td>
                        <td>@truck.GET_IN_DATE</td>
                        <td>@truck.GET_OUT_DATE</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</body>
</html>